version: "3.8"

services:
  servers:
    container_name: servers
    build:
      context: .
      dockerfile: Dockerfile
      target: ${BUILD_TARGET}
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
    ports:
      - "${APP_PORT}:${APP_PORT}"
      - "9229:9229"  # Node.js debug
    networks:
      - nest-net
    volumes:
      - .:/servers
      - upload:/upload
    depends_on:
      - mysql
      - redis

  mysql:
    container_name: mysql
    image: mysql:8
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - nest-net
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    networks:
      - nest-net
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight
    restart: always
    environment:
      - REDISINSIGHT_HOST=0.0.0.0
    networks:
      - nest-net
    ports:
      - "5540:5540"

networks:
  nest-net:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  upload:
